# Generated by Django 5.2.7 on 2026-02-27 13:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_cooked', models.BooleanField(default=False)),
                ('cooked_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomizableHeaders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MainStoreRawItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(choices=[('GRAMS', 'g'), ('LITRE', 'litre'), ('PIECES', 'pieces')], default='PIECES', max_length=20)),
                ('type', models.CharField(choices=[('COUNTABLE', 'Countable'), ('VOLUME', 'Volume')], default='COUNTABLE', max_length=50)),
                ('description', models.TextField()),
                ('quantity_in_stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_batch_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reorder_level', models.PositiveIntegerField()),
                ('should_read_alerts', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(choices=[('GRAMS', 'g'), ('LITRE', 'litre'), ('PIECES', 'pieces')], default='PIECES', max_length=20)),
                ('type', models.CharField(choices=[('COUNTABLE', 'Countable'), ('VOLUME', 'Volume')], default='COUNTABLE', max_length=50)),
                ('description', models.TextField()),
                ('quantity_in_stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_batch_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reorder_level', models.PositiveIntegerField()),
                ('should_read_alerts', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_info', models.TextField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=10)),
                ('endpoint', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BatchProductionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiplier', models.DecimalField(decimal_places=2, help_text='Number of batches produced', max_digits=10)),
                ('produced_at', models.DateTimeField(auto_now_add=True)),
                ('is_reversed', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_logs', to='inventory.batchname')),
                ('produced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_productions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customizables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('unit', models.CharField(choices=[('GRAMS', 'g'), ('LITRE', 'litre'), ('PIECES', 'pieces')], default='PIECES', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='food_images/')),
                ('quantity_if_package', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('price_if_package', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('adjustable', models.BooleanField(default=False)),
                ('self_required_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('self_quantity_in_stock', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('alias', models.CharField(blank=True, max_length=100, null=True)),
                ('pricing_type', models.CharField(choices=[('FIX', 'Fixed'), ('VAR', 'Variable'), ('FIX_VAR', 'Fixed & Variable')], default='FIX', max_length=30)),
                ('array_if_fixed_variable', models.JSONField(blank=True, null=True)),
                ('should_read_alerts', models.BooleanField(default=True)),
                ('customizable_header', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.customizableheaders')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('unit', models.CharField(choices=[('GRAMS', 'g'), ('LITRE', 'litre'), ('PIECES', 'pieces')], default='PIECES', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='food_images/')),
                ('quantity_if_package', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('price_if_package', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('adjustable', models.BooleanField(default=False)),
                ('self_required_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('self_quantity_in_stock', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('alias', models.CharField(blank=True, max_length=100, null=True)),
                ('pricing_type', models.CharField(choices=[('FIX', 'Fixed'), ('VAR', 'Variable'), ('FIX_VAR', 'Fixed & Variable')], default='FIX', max_length=30)),
                ('array_if_fixed_variable', models.JSONField(blank=True, null=True)),
                ('should_read_alerts', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('STANDALONE', 'Standalone'), ('PACKAGES', 'Packages'), ('DEFAULT', 'default')], default='STANDALONE', max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.category')),
                ('products_customs', models.ManyToManyField(blank=True, to='inventory.customizables')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BatchProductionRecipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.DecimalField(decimal_places=2, max_digits=10)),
                ('batch_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.batchname')),
                ('raw_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_item_recipes_products', to='inventory.rawitems')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('PRODUCT', 'Product'), ('CUSTOM', 'Custom'), ('RAW', 'Raw Item'), ('MAIN_STORE_RAW', 'Main Store Raw Item')], default='RAW', max_length=20)),
                ('alert_type', models.CharField(choices=[('LOW_STOCK', 'Low stock'), ('OUT_OF_STOCK', 'Out of stock')], max_length=20)),
                ('severity', models.CharField(choices=[('WARN', 'Warning'), ('CRITICAL', 'Critical')], max_length=10)),
                ('message', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_whatsapp_sent_at', models.DateTimeField(blank=True, null=True)),
                ('main_store_raw_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='inventory.mainstorerawitems')),
                ('raw_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='inventory.rawitems')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('MoMO', 'Mobile Money')], default='CASH', max_length=20)),
                ('specific_description', models.TextField(blank=True, null=True)),
                ('daily_sequence_number', models.PositiveIntegerField(blank=True, null=True)),
                ('sale_status', models.CharField(choices=[('In Queue', 'In queue'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='In Queue', max_length=50)),
                ('is_delivery', models.BooleanField(default=False)),
                ('delivery_number', models.CharField(blank=True, max_length=50, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_sales', to='inventory.customer')),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_sales', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_sales', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('PRODUCT', 'Product'), ('CUSTOM', 'Custom'), ('RAW', 'Raw Item'), ('MAIN_STORE_RAW', 'Main Store Raw Item')], max_length=20)),
                ('adjustment_type', models.CharField(choices=[('WASTAGE', 'Wastage'), ('SPOILAGE', 'Spoilage'), ('LEFTOVER', 'Leftover'), ('CUSTOM_ADD', 'Custom Addition'), ('CUSTOM_DEDUCT', 'Custom Deduction'), ('SYSTEM_CORRECTION_ADD', 'System Reconciliation (+)'), ('SYSTEM_CORRECTION_DEDUCT', 'System Reconciliation (-)'), ('PRODUCTION_DEDUCT', 'Production Deduction'), ('PRODUCTION_REVERSAL', 'Production Reversal (Undo)'), ('DISBURSEMENT_IN', 'Disbursement Received'), ('DISBURSEMENT_OUT', 'Disbursement Sent')], max_length=30)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adjusted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_adjustments', to=settings.AUTH_USER_MODEL)),
                ('custom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustments', to='inventory.customizables')),
                ('main_store_raw_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustments', to='inventory.mainstorerawitems')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustments', to='inventory.products')),
                ('raw_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustments', to='inventory.rawitems')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='rawitems',
            name='supplied_by',
            field=models.ManyToManyField(blank=True, related_name='supplied_raw_items', to='inventory.suppliers'),
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('raw_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='inventory.mainstorerawitems')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='inventory.suppliers')),
            ],
            options={
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.AddField(
            model_name='mainstorerawitems',
            name='supplied_by',
            field=models.ManyToManyField(blank=True, related_name='supplied_main_store_items', to='inventory.suppliers'),
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('PRODUCT', 'Product'), ('CUSTOM', 'Custom')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('price_sold', models.DecimalField(decimal_places=2, max_digits=10)),
                ('custom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.customizables')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.products')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.sale')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('sale', 'product', 'custom'), name='unique_sale_item')],
            },
        ),
    ]
